name: Homebrew

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  formula:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - macos-13
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: brew update
      run: |
        [ -d "/home/linuxbrew/.linuxbrew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew update

    - name: brew install
      run: |
        [ -d "/home/linuxbrew/.linuxbrew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --debug --verbose ./Formula/drogon.rb

    # ref: https://github.com/Homebrew/homebrew-core/issues/135068#issuecomment-1608783869
    - name: brew link binutils
      if: matrix.os == 'ubuntu-20.04'
      run: |
        [ -d "/home/linuxbrew/.linuxbrew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew link --force binutils

    - name: brew test
      run: |
        [ -d "/home/linuxbrew/.linuxbrew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew test --verbose Formula/drogon.rb

    - name: brew audit
      run: |
        [ -d "/home/linuxbrew/.linuxbrew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew audit --verbose --strict drogon
        brew audit --verbose --new drogon
